--#1
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID, SALARY
FROM EMPLOYEES
WHERE SALARY >=10000
ORDER BY JOB_ID, EMPLOYEE_ID

--#2
SELECT EMPLOYEE_ID, LOWER(EMAIL)||'@samsung.com' AS "e-mail"
FROM EMPLOYEES
ORDER BY EMPLOYEE_ID

--#3
SELECT DEPARTMENT_ID, ROUND(AVG(SALARY)) AVG_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(DEPARTMENT_ID)>= 5
ORDER BY DEPARTMENT_ID

--#4
SELECT DEPARTMENT_ID, FIRST_NAME, LAST_NAME, SALARY, CASE DEPARTMENT_ID
														WHEN 30 THEN SALARY*1.3
														WHEN 50 THEN SALARY*1.5
														WHEN 80 THEN SALARY*0.9
														ELSE SALARY END AS NEXT_SALARY
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID ASC, FIRST_NAME DESC

--#5
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID, SALARY
FROM (
	SELECT *
	FROM EMPLOYEES
	ORDER BY SALARY DESC
)
WHERE ROWNUM=1

--#6
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME, J.JOB_TITLE
FROM EMPLOYEES E, JOBS J
WHERE E.JOB_ID = J.JOB_ID AND J.JOB_TITLE LIKE '%Manager'
ORDER BY E.EMPLOYEE_ID DESC

--#7
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, M.FIRST_NAME AS MANAGER_NAME, M.HIRE_DATE AS MGR_HIRE_DATE
FROM EMPLOYEES E, EMPLOYEES M
WHERE E.MANAGER_ID = M.EMPLOYEE_ID(+)
ORDER BY E.EMPLOYEE_ID DESC

--#8
SELECT E.DEPARTMENT_ID, D.DEPARTMENT_NAME, L.CITY, COUNT(*) AS EMPLOYEE_CNT, ROUND(AVG(SALARY)) AS AVG_SAL
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND D.LOCATION_ID = L.LOCATION_ID
AND L.CITY IN('Toronto','London', 'Oxford')
GROUP BY E.DEPARTMENT_ID, D.DEPARTMENT_NAME, L.CITY
ORDER BY E.DEPARTMENT_ID

--#9
UPDATE JOBS
SET JOB_TITLE = 'Solution Programmer', MAX_SALARY = 50000
WHERE JOB_ID = 'IT_PROG'
--SELECT *
--FROM JOBS
--WHERE JOB_ID = 'IT_PROG'

